import './globals.css'
import { Inter } from 'next/font/google'
import UtilityLibrary from '@/src/libraries/UtilityLibrary'

const inter = Inter({ subsets: ['latin'] })


console.log('error')
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function setAndAppendStyles() {
  const head = document.head;
  const style = document.createElement('style');
  const css = `
  [social].instagram [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/instagram.png')}");
      background-size: 100%;
  }
  [social].facebook [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/facebook.png')}");
      background-size: 100%;
  }
  [social].twitter [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/twitter.png')}");
      background-size: 100%;
  }
  [social].github [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/github.png')}");
      background-size: 100%;
      background-color: white;
      border-radius: 100%;
  }
  [social].deviantart [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/deviantart.png')}");
      background-size: 100%;
  }
  [social].behance [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/behance.png')}");
      background-size: 100%;
  }
  [social].flickr [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/flickr.png')}");
      background-size: 100%;
  }
  [social].foundationapp [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/foundationapp.png')}");
      background-size: 100%;
  }
  [social].opensea [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/opensea.png')}");
      background-size: 100%;
  }
  [social].superrare [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/superrare.png')}");
      background-size: 100%;
  }
  [social].discord [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/discord.png')}");
      background-size: 100%;
  }
  [social].keybase [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/keybase.png')}");
      background-size: 100%;
  }
  [social].linkedin [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('icons/linkedin.png')}");
      background-size: 100%;
  }
  [brand] [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('images/rodrigo-barraza-logo.png')}");
  }
  [brand]:hover [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('images/rodrigo-barraza-logo-animated.gif')}");
  }
  [name] [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('images/rodrigo-barraza-logo.png')}");
  }
  [name]:hover [logo] {
      background-image: url("${UtilityLibrary.renderAssetPath('images/rodrigo-barraza-logo-animated.gif')}");
  }`
  head.appendChild(style);
  style.type = 'text/css';
  style.appendChild(document.createTextNode(css));
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
