import './globals.css'
import { Inter } from 'next/font/google'
import UtilityLibrary from '@/src/libraries/UtilityLibrary'

const inter = Inter({ subsets: ['latin'] })


console.log('error')
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
