const PromptCollection = [
    { prompt: 'A close-up photograph portrait of Sailor Moon' },
    { prompt: 'A close-up photograph portrait of Vegeta, man with pointy hair' },
    { prompt: 'A close-up photograph portrait of a penguin in the arctic' },
    { prompt: 'A close-up photograph portrait of Bill Gates!' },
    { prompt: 'A close-up photograph portrait of Joe' },
    { prompt: 'A close-up photograph portrait of sailors' },
    { prompt: 'a photograph portrait of an orc warlock man laughing with mouth open holding a beer bottle' },
    { prompt: 'A stunning close-up photograph captures the charm and charisma of Emma Watson.' },
    { prompt: 'A black and white close-up photograph of Audrey Hepburn showcases her timeless beauty and elegance.' },
    { prompt: 'This close-up photograph of Beyoncé commands attention with her fierce gaze and striking features.' },
    { prompt: 'The close-up photograph of Barack Obama captures his calm and confident demeanor, exuding leadership and authority.' },
    { prompt: 'A close-up photograph of Angelina Jolie captures her intense gaze and alluring features, leaving a lasting impression on the viewer.' },
    { prompt: 'This close-up photograph of Johnny Depp captures his enigmatic persona, leaving the viewer intrigued and captivated.' },
    { prompt: 'A close-up photograph of Lady Gaga showcases her bold and fearless nature, exuding confidence and individuality.' },
    { prompt: 'This close-up photograph of Princess Diana captures her natural beauty and grace, leaving a lasting impact on the viewer.' },
    { prompt: 'A close-up photograph of Will Smith showcases his infectious smile and magnetic personality, radiating positivity and charm.' },
    { prompt: 'This close-up photograph of Marilyn Monroe captures her iconic beauty and timeless allure, leaving a lasting impression on the viewer.' },
    { prompt: 'A close-up photograph of Dwayne Johnson captures his rugged and handsome features, exuding strength and charisma.' },
    { prompt: 'This close-up photograph of Michelle Obama captures her warm and approachable nature, inspiring and empowering women around the world.' },
    { prompt: 'A close-up photograph of Adele showcases her raw and powerful vocals, capturing the essence of her soulful music.' },
    { prompt: 'This close-up photograph of Heath Ledger captures his intense and brooding gaze, leaving a lasting impression on the viewer.' },
    { prompt: 'A close-up photograph of Rihanna showcases her bold and edgy style, exuding confidence and individuality.' },
    { prompt: 'This close-up photograph of Leonardo DiCaprio captures his piercing blue eyes and rugged features, leaving the viewer captivated.' },
    { prompt: 'A close-up photograph of Selena Gomez showcases her natural beauty and youthful charm, captivating the hearts of her fans.' },
    { prompt: 'This close-up photograph of David Beckham captures his chiseled jawline and rugged features, exuding masculinity and charm.' },
    { prompt: 'A stunning close-up photograph of Wonder Woman, woman with flowing hair and tiara, ready to fight for justice.' },
    { prompt: 'A breathtaking close-up photograph of Thor, man with a majestic hammer and flowing blonde hair, ready to defend Asgard.' },
    { prompt: 'An exquisite close-up photograph of Black Panther, man with a fierce mask and sleek black suit, ready to protect Wakanda.' },
    { prompt: 'A captivating close-up photograph of Elsa, woman with a magical ice crown and flowing blonde hair, ready to unleash her powers.' },
    { prompt: 'An impressive close-up photograph of Iron Man, man with a high-tech suit and glowing arc reactor, ready to save the world.' },
    { prompt: 'A striking close-up photograph of Harley Quinn, woman with colorful hair and a wicked smile, ready to cause chaos in Gotham.' },
    { prompt: 'A mesmerizing close-up photograph of Spider-Man, man with a red and blue suit and a web-slinging pose, ready to swing into action.' },
    { prompt: 'A powerful close-up photograph of Goku, man with spiky black hair and a determined expression, ready to unleash his energy.' },
    { prompt: 'An amazing close-up photograph of Captain America, man with a patriotic shield and a determined gaze, ready to defend his country.' },
    { prompt: 'A dynamic close-up photograph of Catwoman, woman with a sleek black suit and a feline grace, ready to steal the night.' },
    { prompt: 'A stunning close-up photograph of Superman, man with a red cape and a heroic stance, ready to save the day.' },
    { prompt: 'A striking close-up photograph of Mystique, woman with blue skin and a shapeshifting ability, ready to blend in with any crowd.' },
    { prompt: 'A captivating close-up photograph of Wolverine, man with retractable claws and a fierce expression, ready to take on any enemy.' },
    { prompt: 'A photograph of the actor known as tom hanks, playing the role, forest gump in the movie forest gump.' },
];

export default PromptCollection;
  